server:
  port: 80
spring:
  mail:
    username: 1227900499@qq.com
    password: bznrhjljaylpffji
    host: smtp.qq.com


# 启用端点 env
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  # 暴露端点 env 配置多个,隔开
