
#server:
#  port: 80
#spring:
#  mail:
#    username: 1227900499@qq.com
#    password: bznrhjljaylpffji
#    host: smtp.qq.com
#  datasource:
##    type: com.zaxxer.hikari.HikariDataSource
##    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://152.32.192.200:3306/blogdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
#    username: blog
#    password: 'privateblog'

# 启用端点 env
#management:
#  endpoint:
#    env:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'
  # 暴露端点 env 配置多个,隔开




#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations:
#    - classpath*:mapper/**/*-mapper.xml
#    - classpath*:mapper/**/*-mapper-ext.xml